version: 0.2 

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing Maven Wrapper"
      - mvn -N io.takari:maven:wrapper
  build:
    commands:
      - echo "Building with Maven"
      - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - echo "Running Unit Tests"
      - ./mvnw test
      - echo "Running Integration Tests"
      - ./mvnw integration-test
  post_build:
    commands:
      - echo "Build completed on `date`"
artifacts:
  files:
    - target/*.jar
  name: demo
  discard-paths: yes
      